version: '3.8'

services:
  java-backend:
    image: stock-predictor-ml:latest
    container_name: java-backend
    ports:
      - "8080:8080"
    networks:
      - app-network
mysql:
    image: mysql:8.0
    container_name: stock-predictor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
