name: CI Pipeline - Stock Predictor ML

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  java-backend:
    name: Build & Test Java Backend
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'


      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-


      - name: Build with Maven
        run: mvn clean install


  #   name: Test Python Microservice
  #   runs-on: ubuntu-latest
  #   steps:
  #
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     # Set up Python
  #     - name: Set up Python
  #       uses: actions/setup-python@v5
  #       with:
  #         python-version: '3.12'

  #
  #     - name: Install Python dependencies
  #       run: |
  #         cd com.daniel.stockpredictorml.python-com.daniel.stockpredictorml.service
  #         pip install --upgrade pip
  #         pip install -r requirements.txt

  #
  #     - name: Run Python tests
  #       run: |
  #         cd com.daniel.stockpredictorml.python-com.daniel.stockpredictorml.service
  #         pytest --maxfail=1 --disable-warnings -q

